name: Backend Deploy to EC2

on:
  push:
    branches:
      - main
    paths:
      - "backend/**"
      - "docker-compose.yml"
      - ".github/workflows/backend-pipeline.yml"

jobs:
  backend-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Deploy backend on EC2
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_KEY }}
          envs: |
            SPRING_DATA_MONGODB_URI=${{ secrets.SPRING_DATA_MONGODB_URI }}
            VISUAL_INTERNAL_API_KEY=${{ secrets.VISUAL_INTERNAL_API_KEY }}
            JWT_SECRET=${{ secrets.JWT_SECRET }}
          script: |
            set -e
            cd ~/MULE_HUNTER
            git pull origin main
            cat <<EOF > .env
            SPRING_DATA_MONGODB_URI=$SPRING_DATA_MONGODB_URI
            VISUAL_INTERNAL_API_KEY=$VISUAL_INTERNAL_API_KEY
            JWT_SECRET=$JWT_SECRET
            EOF
            # docker-compose down
            # docker-compose up -d --build 
            echo "Clearing port 8082..."
            docker ps -q --filter "publish=8082" | xargs -r docker stop
            docker ps -aq --filter "publish=8082" | xargs -r docker rm -f
            docker-compose up -d --build --no-deps backend
            docker image prune -f